name: LibrosyReview CI/CD Pipeline

# Ejecutar el workflow cuando se haga push o pull request a main/master/libros
on:
  push:
    branches: [ main, master, libros ]
  pull_request:
    branches: [ main, master, libros ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    # Instalar dependencias del proyecto librosyreview
    - name: Install dependencies
      run: |
        cd librosyreview
        npm ci
        
    # Ejecutar tests
    - name: Run tests
      run: |
        cd librosyreview
        npm test -- --watchAll=false
        
    # Construir la aplicación
    - name: Build application
      run: |
        cd librosyreview
        npm run build
        
    # Desplegar a Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./librosyreview
        vercel-args: '--prod'